# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountDt', models.CharField(max_length=200)),
                ('segmentDt1', models.CharField(max_length=200)),
                ('segmentDt2', models.CharField(max_length=200)),
                ('segmentDt3', models.CharField(max_length=200)),
                ('segmentDt4', models.CharField(max_length=200)),
                ('segmentDt5', models.CharField(max_length=200)),
                ('segmentDt6', models.CharField(max_length=200)),
                ('segmentDt7', models.CharField(max_length=200)),
                ('segmentDt8', models.CharField(max_length=200)),
                ('segmentDt9', models.CharField(max_length=200)),
                ('segmentDt10', models.CharField(max_length=200)),
                ('accountKt', models.CharField(max_length=200)),
                ('segmentKt2', models.CharField(max_length=200)),
                ('segmentKt3', models.CharField(max_length=200)),
                ('segmentKt4', models.CharField(max_length=200)),
                ('segmentKt5', models.CharField(max_length=200)),
                ('segmentKt6', models.CharField(max_length=200)),
                ('segmentKt7', models.CharField(max_length=200)),
                ('segmentKt8', models.CharField(max_length=200)),
                ('segmentKt9', models.CharField(max_length=200)),
                ('segmentKt10', models.CharField(max_length=200)),
                ('sumOperaton', models.FloatField()),
            ],
        ),
    ]
